name: CI-CD

on:
  push:
    branches: ["main"]
    paths-ignore: 
      - './k8s/**'
      - './github/**'
      - 'README.md'
  workflow_dispatch:
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Obter o código do projeto
        uses: actions/checkout@v4
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Contrução da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          file: ./Dockerfile
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/ecommerce-desafio-k8s:v${{ github.run_number }}
            ${{ vars.DOCKERHUB_USERNAME }}/ecommerce-desafio-k8s:latest
  cd:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    needs: [ci]
    steps: 
      - name: Obter o código do projeto
        uses: actions/checkout@v4
      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Configurar o kubectl
        run: aws eks update-kubeconfig --name K8S-CLUSTER
      - name: Deploy dos manifestos no Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/ecommerce-deployment.yaml
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/ecommerce-desafio-k8s:v${{ github.run_number }}
